name: Run tests

on:
  push:
    branches: [ "imgui" ]
  pull_request:
    branches: [ "imgui" ]
  workflow_dispatch:

env:
  LOVE_ARTIFACT_URL: "https://api.github.com/repos/love2d/love/actions/artifacts/1580582511/zip"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Install luacov
      run: |
        sudo apt install luarocks
        sudo luarocks --lua-version 5.1 install luacov

    - name: Get love
      run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --output love12.zip --url "${{ env.LOVE_ARTIFACT_URL }}"
        7z x love12.zip
        chmod +x love-*.AppImage

    - name: Run tests
      run: |
        COVERAGE=1 AUTOTEST=1 AUTOCLOSE=1 xvfb-run ./love-*.AppImage .

    - name: Coverage
      run: |
        luacov
        cat luacov.report.out
